### ISSUE TITLE
Infinite Loop issues

### ISSUE THREAD

**Issue by bradennapier** [RubyLane/rl_json#11]
Hey Cyan,
  So I've been dealing with a really crazy bug I haven't been able to track down now for weeks.  At some point I suddenly start getting non-stop infinite loop errors reported.  It is always in a different place in my code and seems to be completely random.  

  I did notice most of the problems were coming from some sort of JSON-related proc.  I believe I have narrowed this down to rl_json, specifically perhaps the [foreach] command.  Tcl chatroom mentioned it is quite possibly a problem if it isn't NRE enabled and i just noticed in source you have that as a todo.

  Anyways, going to try switching to just using json get and then looping it from there, but wanted to mention it in the meantime.  

   My guess is the API spits out some weird code that ends up causing the issue.

**Comment by cyanogilvie** [comment]
I've finally had a stab at NRE enabling [json foreach] and [json lmap].  I haven't used the NRE mechanisms before and a complex loop construct like foreach is a bit more complex than the trivial cases in the examples, so I'm not yet completely confident that the code is sound.  It passes the tests and gets a clean bill of health from valgrind though.

If your issue is still happening and you're in a position to test the 0.9.8b1 version to see if it helps, then please let me know.
