### ISSUE TITLE
Patch for making the code work on windows

### ISSUE THREAD

**Issue by ecky-l** [RubyLane/rl_json#14]
Hello,

I created a patch to make the code work on windows. The main part is the "BitScanForward()" function, in place of the unix only ffsll() function. And the __VA_ARGS__ variable argument macro expansion, which was also not compilable with MSVC.
All the tests run through. Apart from the tests which check against funny unicode characters - but I think this is an encoding problem on windows. If  the unicode characters are replaced by their \u... sequence in the test file, everything works and all tests are green.

In parser.h is a struct definition interp_cx, with a field interp_cx.freemap. It was defined as long long, with a remark that this is needed for ffsll(). I changed the definition to unsigned long, since that was more compatible with the Windows version of that function BitScanForward().. I found out that on linux it does also not have any consequences, for my test runs, compilation etc. it didn't matter whether its long long or unsigned long. Would it be an option to change that to unsigned long generally?

Apart from that, I think the patch needs some review and cleanup, but it would be good to incorporate it for the windows users :).

[rl_json_el.zip](https://github.com/RubyLane/rl_json/files/1022300/rl_json_el.zip)

**Comment by ecky-l** [comment]
Oh, I just saw that some code has changed on the master. My patch is against version 0.9.7
I think I have to rework it a little to make it compatible with master...

**Comment by cyanogilvie** [comment]
Hi

There is an open pull request with a set of patches that let it build in
visual studio that addresses the same areas. I haven't merged it yet
because there are some issues that will take a bit of work to do properly.

That branch has a hand-coded version of ffsll, and I've played with a few
variants of that. The BitScanForward function seemed like a reasonable
alternative on windows but that area is really subtle so it would have to
be very deeply understood to safely change.  The reason for all this
complexity is that it gives the compiler and standard libraries a fighting
chance of being able to use one of the machine code opcodes dedicated to
that job (available on nearly every common cpu). That's important because
it's very hot code in the area that is the bottleneck for my benchmarks.

Thanks for the patch. I'll have to take a look at it properly after work
today.  In the mean time, the encoding issue in the tests sounds like the
system encoding is something other than utf-8, so the test file isn't being
loaded properly.

Cyan

On 23 May 2017 3:37 PM, "ecky-l" <notifications@github.com> wrote:

Hello,

I created a patch to make the code work on windows. The main part is the
"BitScanForward()" function, in place of the unix only ffsll() function.
And the *VA_ARGS* variable argument macro expansion, which was also not
compilable with MSVC.
All the tests run through. Apart from the tests which check against funny
unicode characters - but I think this is an encoding problem on windows. If
the unicode characters are replaced by their \u... sequence in the test
file, everything works and all tests are green.

in parser.h is a struct definition interp_cx, with a field
interp_cx.freemap. It was defined as long long, with a remark that this is
needed for ffsll(). I changed the definition to unsigned long, since that
was more compatible with the Windows version of that funktion
BitScanForward().. I found out that on linux it does also not have any
consequences, for my test runs, compilation etc. it didn't matter whether
its long long or unsigned long. Would it be an option to change that to
long long generally?

Apart from that, I think the patch needs some review and cleanup, but it
would be good to incorporate it for the windows users :).

Patch below, apparently its not possible to attach such files here...

`
diff -ruN rl_json/generic/main.c rl_json_el/generic/main.c
--- rl_json/generic/main.c 2017-05-23 15:21:09.412122000 +0200
+++ rl_json_el/generic/main.c 2017-05-03 13:40:45.224891900 +0200
@@ -1,5 +1,9 @@
#include "main.h"

+#ifdef WIN32
+#include <intrin.h>
+#endif
+
static void free_internal_rep(Tcl_Obj* obj);
static void dup_internal_rep(Tcl_Obj* src, Tcl_Obj* dest);
static void update_string_rep(Tcl_Obj* obj);
@@ -104,31 +108,38 @@
};

static int new_json_value_from_list(Tcl_Interp* interp, int objc,
Tcl_Obj *const
objv[], Tcl_Obj** res);
-static int NRforeach_next_loop_bottom(ClientData cdata[], Tcl_Interp*
interp, int retcode);

-static int first_free(long long* freemap) //{{{
+static int first_free(unsigned long* freemap) //{{{
{
int i=0, bit, res;
+
+#ifndef WIN32
while ((bit = ffsll(freemap[i])) == 0) {
i++;
}

   - res = i * (sizeof(long long)*8) + (bit-1);
   +#else


   - unsigned long idx = 0;
   - while (_BitScanForward(&idx, freemap[i]) == 0)
   - i++;
   - bit = idx+1;
   +#endif
   - res = i * (sizeof(unsigned long)*8) + (bit-1);
   return res;
   }

//}}}
-static void mark_used(long long* freemap, int idx) //{{{
+static void mark_used(unsigned long* freemap, int idx) //{{{
{

   - int i = idx / (sizeof(long long)*8);
   - int bit = idx - (i * (sizeof(long long)*8));


   - int i = idx / (sizeof(unsigned long)*8);
   - int bit = idx - (i * (sizeof(unsigned long)*8));
   freemap[i] &= ~(1LL << bit);
   }

//}}}
-static void mark_free(long long* freemap, int idx) //{{{
+static void mark_free(unsigned long* freemap, int idx) //{{{
{

   - int i = idx / (sizeof(long long)*8);
   - int bit = idx - (i * (sizeof(long long)*8));


   - int i = idx / (sizeof(unsigned long)*8);
   - int bit = idx - (i * (sizeof(unsigned long)*8));
   freemap[i] |= 1LL << bit;
   }

@@ -673,6 +684,7 @@
//}}}
static int set_from_any(Tcl_Interp* interp, Tcl_Obj* obj) //{{{
{

   - Tcl_CmdInfo parse_cmd;
   struct interp_cx* l;
   const unsigned char* err_at = NULL;
   const char* errmsg = "Illegal character";
   @@ -686,7 +698,8 @@
   int len;
   struct parse_context cx[CX_STACK_SIZE];


   - l = Tcl_GetAssocData(interp, "rl_json", NULL);


   -

   if (Tcl_GetCommandInfo(interp, "::rl_json::json", &parse_cmd) != 1)
   return TCL_ERROR;
   -

   l = parse_cmd.objClientData;

   cx[0].prev = NULL;
   cx[0].last = cx;
   @@ -1700,7 +1713,6 @@
   "false",
   "null",
   "boolean",


   -

     "json",
     (char*)NULL

   };
   enum {
   @@ -1711,8 +1723,7 @@
   NEW_TRUE,
   NEW_FALSE,
   NEW_NULL,
   -

     NEW_BOOL,

   -

     NEW_JSON



   -

     NEW_BOOL

   };

   if (objc < 1) CHECK_ARGS(0, "type ?val?");
   @@ -1820,18 +1831,6 @@
   }
   break;
   //}}}


   -

     case NEW_JSON: //{{{

   -

     	{

   -

     		int _type;

   -

     		Tcl_Obj *_val;

   -
   -

     		CHECK_ARGS(1, "json val");

   -

     		TEST_OK(JSON_GetJvalFromObj(interp, objv[1], &_type, &_val));

   -

     		*res = objv[1];

   -

     		Tcl_IncrRefCount(objv[1]);

   -

     	}

   -

     	break;

   -

     	//}}}
     default:
     	THROW_ERROR("Invalid new_type: ", Tcl_GetString(Tcl_NewIntObj(new_type)));

   }
   @@ -1840,149 +1839,43 @@
   }

//}}}
-static void foreach_state_free(struct foreach_state* state) //{{{
-{

   - int i;
   -
   - Tcl_DecrRefCount(state->script);
   - state->script = NULL;
   -
   - // Close any pending searches
   - for (i=0; iiterators; i++)
   -

     if (state->it[i].search.dictionaryPtr != NULL)

   -

     	Tcl_DictObjDone(&state->it[i].search);

   -
   - if (state->it != NULL) {
   -

     Tcl_Free((char*)state->it);

   -

     state->it = NULL;

   - }
   -
   - if (state->res != NULL) {
   -

     Tcl_DecrRefCount(state->res);

   -

     state->res = NULL;

   - }
   -}
   -

-//}}}
-static int NRforeach_next_loop_top(Tcl_Interp* interp, struct
foreach_state* state) //{{{
-{

   - int j, k;
   -
   - //fprintf(stderr, "Starting iteration %d/%d\n", i, max_loops);
   - // Set the iterator variables
   - for (j=0; j < state->iterators; j++) {
   -

     struct foreach_iterator* this_it = &state->it[j];

   -
   -

     if (this_it->is_array) { // Iterating over a JSON array

   -

     	//fprintf(stderr, "Array iteration, data_i: %d, length %d\n",
this_it->data_i, this_it->data_c);

   -

     	for (k=0; k<this_it->var_c; k++) {

   -

     		Tcl_Obj* it_val;

   -
   -

     		if (this_it->data_i < this_it->data_c) {

   -

     			//fprintf(stderr, "Pulling next element %d off the data list
(length %d)\n", this_it->data_i, this_it->data_c);

   -

     			it_val = this_it->data_v[this_it->data_i++];

   -

     		} else {

   -

     			struct interp_cx* l = Tcl_GetAssocData(interp, "rl_json", NULL);

   -

     			//fprintf(stderr, "Ran out of elements in this data list,
setting null\n");

   -

     			it_val = l->json_null;

   -

     		}

   -

     		//fprintf(stderr, "pre  Iteration %d, this_it: %p, setting var
%p, varname ref: %d\n",

   -

     		//		i, this_it, this_it->var_v[k]/*,
Tcl_GetString(this_it->var_v[k])*/, this_it->var_v[k]->refCount);

   -

     		//fprintf(stderr, "varname: \"%s\"\n", Tcl_GetString(it[j].var_v[k]));

   -

     		//Tcl_ObjSetVar2(interp, this_it->var_v[k], NULL, it_val, 0);

   -

     		Tcl_ObjSetVar2(interp, this_it->var_v[k], NULL, it_val, 0);

   -

     		//Tcl_ObjSetVar2(interp, Tcl_NewStringObj("elem", 4), NULL, it_val, 0);

   -

     		//fprintf(stderr, "post Iteration %d, this_it: %p, setting var
%p, varname ref: %d\n",

   -

     		//		i, this_it, this_it->var_v[k]/*,
Tcl_GetString(this_it->var_v[k])*/, this_it->var_v[k]->refCount);

   -

     	}

   -

     } else { // Iterating over a JSON object

   -

     	//fprintf(stderr, "Object iteration\n");

   -

     	if (!this_it->done) {

   -

     		// We check that this_it->var_c == 2 in the setup

   -

     		Tcl_ObjSetVar2(interp, this_it->var_v[0], NULL, this_it->k, 0);

   -

     		Tcl_ObjSetVar2(interp, this_it->var_v[1], NULL, this_it->v, 0);

   -

     		Tcl_DictObjNext(&this_it->search, &this_it->k, &this_it->v,
&this_it->done);

   -

     	}

   -

     }

   - }
   -
   - Tcl_NRAddCallback(interp, NRforeach_next_loop_bottom, state, NULL,
   NULL, NULL);
   - return Tcl_NREvalObj(interp, state->script, 0);
   -}
   -

-//}}}
-static int NRforeach_next_loop_bottom(ClientData cdata[], Tcl_Interp*
interp, int retcode) //{{{
-{

   - struct foreach_state* state = (struct foreach_state*)cdata[0];
   -
   - switch (retcode) {
   -

     case TCL_OK:

   -

     	if (state->res != NULL) // collecting

   -

     		TEST_OK_LABEL(done, retcode, Tcl_ListObjAppendElement(interp,
state->res, Tcl_GetObjResult(interp)));

   -

     	break;

   -
   -

     case TCL_CONTINUE:

   -

     	retcode = TCL_OK;

   -

     	break;

   -
   -

     case TCL_BREAK:

   -

     	retcode = TCL_OK;

   -

     	// falls through

   -

     default:

   -

     	goto done;

   - }
   -
   - state->loop_num++;
   -
   - if (state->loop_num < state->max_loops) {
   -

     return NRforeach_next_loop_top(interp, state);

   - } else {
   -

     if (state->res != NULL) {

   -

     	Tcl_SetObjResult(interp, state->res);

   -

     }

   - }
   -

-done:

   - //fprintf(stderr, "done\n");
   - if (retcode == TCL_OK && state->res != NULL /* collecting */)
   -

     Tcl_SetObjResult(interp, state->res);

   -
   - foreach_state_free(state);
   - Tcl_Free((char*)state);
   - state = NULL;
   -
   - return retcode;
   -}
   -

-//}}}
static int foreach(Tcl_Interp* interp, int objc, Tcl_Obj *const objv[], int
collecting) //{{{
{

   - // Caller must ensure that objc is valid
   - int i, retcode=TCL_OK;
   - struct foreach_state* state = NULL;


   - struct iterator {
   -

     int				data_c;

   -

     Tcl_Obj**		data_v;

   -

     int				data_i;

   -

     int				var_c;

   -

     Tcl_Obj**		var_v;

   -

     int				is_array;

   -
   -

     // Dict search related state - when iterating over JSON objects

   -

     Tcl_DictSearch	search;

   -

     Tcl_Obj*		k;

   -

     Tcl_Obj*		v;

   -

     int				done;

   - };


   - state = (struct foreach_state*)Tcl_Alloc(sizeof(*state));
   - state->iterators = (objc-1)/2;
   - state->it = (struct foreach_iterator*)Tcl_Alloc(sizeof(struct
   foreach_iterator) * state->iterators);
   - state->max_loops = 0;
   - state->loop_num = 0;


   - // Caller must ensure that objc is valid
   - int i, j, k, iterators=(objc-1)/2, max_loops=0, retcode=TCL_OK;
   - Tcl_Obj* script = objv[objc-1];
   - Tcl_Obj* null;
   - Tcl_Obj* res = NULL;
   - //struct iterator it[iterators];
   - struct iterator *it = ckalloc(iterators*sizeof(struct iterator));


   - Tcl_IncrRefCount(state->script = objv[objc-1]);


   - Tcl_IncrRefCount(script);


   - if (collecting) {
   -

     Tcl_IncrRefCount(state->res = Tcl_NewListObj(0, NULL));

   - } else {
   -

     state->res = NULL;



   - for (i=0; i<iterators; i++) {
   -

     it[i].search.dictionaryPtr = NULL;

   -

     it[i].data_v = NULL;

   -

     it[i].is_array = 0;

   -

     it[i].var_v = NULL;

   }


   - for (i=0; iiterators; i++) {
   -

     state->it[i].search.dictionaryPtr = NULL;

   -

     state->it[i].data_v = NULL;

   -

     state->it[i].is_array = 0;

   -

     state->it[i].var_v = NULL;

   - }


   - Tcl_IncrRefCount(null = JSON_NewJvalObj(JSON_NULL, NULL));


   - for (i=0; iiterators; i++) {


   - for (i=0; i<iterators; i++) {
   int loops, type;
   Tcl_Obj* val;
   Tcl_Obj* varlist = objv[i*2];
   @@ -1990,35 +1883,35 @@
   if (Tcl_IsShared(varlist))
   varlist = Tcl_DuplicateObj(varlist);


   -

     TEST_OK_LABEL(done, retcode, Tcl_ListObjGetElements(interp,
varlist, &state->it[i].var_c, &state->it[i].var_v));



   -

     TEST_OK_LABEL(done, retcode, Tcl_ListObjGetElements(interp,
varlist, &it[i].var_c, &it[i].var_v));



   -

     if (state->it[i].var_c == 0)



   -

     if (it[i].var_c == 0)
     	THROW_ERROR_LABEL(done, retcode, "foreach varlist is empty");

     TEST_OK_LABEL(done, retcode, JSON_GetJvalFromObj(interp,
objv[i*2+1], &type, &val));
     switch (type) {
     	case JSON_ARRAY:
     		TEST_OK_LABEL(done, retcode,



   -

     				Tcl_ListObjGetElements(interp, val, &state->it[i].data_c,
&state->it[i].data_v));

   -

     		state->it[i].data_i = 0;

   -

     		state->it[i].is_array = 1;

   -

     		loops = (int)ceil(state->it[i].data_c / (double)state->it[i].var_c);



   -

     				Tcl_ListObjGetElements(interp, val, &it[i].data_c, &it[i].data_v));

   -

     		it[i].data_i = 0;

   -

     		it[i].is_array = 1;

   -

     		loops = (int)ceil(it[i].data_c / (double)it[i].var_c);

     		break;

     	case JSON_OBJECT:



   -

     		if (state->it[i].var_c != 2)



   -

     		if (it[i].var_c != 2)
     			THROW_ERROR_LABEL(done, retcode, "When iterating over a JSON
object, varlist must be a pair of varnames (key value)");

     		TEST_OK_LABEL(done, retcode, Tcl_DictObjSize(interp, val, &loops));



   -

     		TEST_OK_LABEL(done, retcode, Tcl_DictObjFirst(interp, val,
&state->it[i].search, &state->it[i].k, &state->it[i].v,
&state->it[i].done));



   -

     		TEST_OK_LABEL(done, retcode, Tcl_DictObjFirst(interp, val,
&it[i].search, &it[i].k, &it[i].v, &it[i].done));
     		break;

     	case JSON_NULL:



   -

     		state->it[i].data_c = 0;

   -

     		state->it[i].data_v = NULL;

   -

     		state->it[i].data_i = 0;

   -

     		state->it[i].is_array = 1;



   -

     		it[i].data_c = 0;

   -

     		it[i].data_v = NULL;

   -

     		it[i].data_i = 0;

   -

     		it[i].is_array = 1;
     		loops = 0;
     		break;


@@ -2026,22 +1919,88 @@
THROW_ERROR_LABEL(done, retcode, "Cannot iterate over JSON type ",
type_names[type]);
}

   -

     if (loops > state->max_loops)

   -

     	state->max_loops = loops;



   -

     if (loops > max_loops)

   -

     	max_loops = loops;

   }


   - if (state->loop_num < state->max_loops)
   -

     return NRforeach_next_loop_top(interp, state);



   - if (collecting)
   -

     res = Tcl_NewListObj(0, NULL);

   -
   - for (i=0; i<max_loops; i++) {
   -

     //fprintf(stderr, "Starting iteration %d/%d\n", i, max_loops);

   -

     // Set the iterator variables

   -

     for (j=0; j<iterators; j++) {

   -

     	struct iterator* this_it = &it[j];

   -
   -

     	if (this_it->is_array) { // Iterating over a JSON array

   -

     		//fprintf(stderr, "Array iteration, data_i: %d, length %d\n",
this_it->data_i, this_it->data_c);

   -

     		for (k=0; k<this_it->var_c; k++) {

   -

     			Tcl_Obj* it_val;

   -
   -

     			if (this_it->data_i < this_it->data_c) {

   -

     				//fprintf(stderr, "Pulling next element %d off the data list
(length %d)\n", this_it->data_i, this_it->data_c);

   -

     				it_val = this_it->data_v[this_it->data_i++];

   -

     			} else {

   -

     				//fprintf(stderr, "Ran out of elements in this data list,
setting null\n");

   -

     				it_val = null;

   -

     			}

   -

     			//fprintf(stderr, "pre  Iteration %d, this_it: %p, setting var
%p, varname ref: %d\n",

   -

     			//		i, this_it, this_it->var_v[k]/*,
Tcl_GetString(this_it->var_v[k])*/, this_it->var_v[k]->refCount);

   -

     			//fprintf(stderr, "varname: \"%s\"\n", Tcl_GetString(it[j].var_v[k]));

   -

     			//Tcl_ObjSetVar2(interp, this_it->var_v[k], NULL, it_val, 0);

   -

     			Tcl_ObjSetVar2(interp, this_it->var_v[k], NULL, it_val, 0);

   -

     			//Tcl_ObjSetVar2(interp, Tcl_NewStringObj("elem", 4), NULL, it_val, 0);

   -

     			//fprintf(stderr, "post Iteration %d, this_it: %p, setting var
%p, varname ref: %d\n",

   -

     			//		i, this_it, this_it->var_v[k]/*,
Tcl_GetString(this_it->var_v[k])*/, this_it->var_v[k]->refCount);

   -

     		}

   -

     	} else { // Iterating over a JSON object

   -

     		//fprintf(stderr, "Object iteration\n");

   -

     		if (!this_it->done) {

   -

     			// We check that this_it->var_c == 2 in the setup

   -

     			Tcl_ObjSetVar2(interp, this_it->var_v[0], NULL, this_it->k, 0);

   -

     			Tcl_ObjSetVar2(interp, this_it->var_v[1], NULL, this_it->v, 0);

   -

     			Tcl_DictObjNext(&this_it->search, &this_it->k, &this_it->v,
&this_it->done);

   -

     		}

   -

     	}

   -

     }

   -
   -

     // TODO: NRE enable

   -

     retcode = Tcl_EvalObjEx(interp, script, 0);

   -
   -

     switch (retcode) {

   -

     	case TCL_OK:

   -

     		if (collecting)

   -

     			TEST_OK_LABEL(done, retcode, Tcl_ListObjAppendElement(interp,
res, Tcl_GetObjResult(interp)));

   -

     		break;

   -
   -

     	case TCL_CONTINUE:

   -

     		retcode = TCL_OK;

   -

     		break;

   -
   -

     	case TCL_BREAK:

   -

     		retcode = TCL_OK;

   -

     		// falls through

   -

     	default:

   -

     		goto done;

   -

     }

   - }

done:
//fprintf(stderr, "done\n");

   -

   if (retcode == TCL_OK && collecting)
   -

     Tcl_SetObjResult(interp, state->res);

   -

   foreach_state_free(state);
   -

   Tcl_Free((char*)state);
   -

   state = NULL;


   -

   Tcl_DecrRefCount(script);
   -
   -

   // Close any pending searches
   -

   for (i=0; i<iterators; i++)
   -

     if (it[i].search.dictionaryPtr != NULL)

   -

     	Tcl_DictObjDone(&it[i].search);

   -

   Tcl_DecrRefCount(null);
   -
   -

   if (retcode == TCL_OK && collecting)
   -

     Tcl_SetObjResult(interp, res);

   -
   -

   ckfree(it);
   return retcode;
   }

@@ -2248,7 +2207,7 @@

//}}}
#endif
-static int jsonNRObjCmd(ClientData cdata, Tcl_Interp* interp, int objc,
Tcl_Obj
*const objv[]) //{{{ +static int jsonObjCmd(ClientData cdata, Tcl_Interp*
interp, int objc, Tcl_Obj *const objv[]) //{{{
{
int method, retcode=TCL_OK;
static const char *methods[] = {
@@ -2631,12 +2590,6 @@
}

//}}}
-static int jsonObjCmd(ClientData cdata, Tcl_Interp* interp, int objc,
Tcl_Obj *const objv[]) //{{{
-{

   - return Tcl_NRCallObjProc(interp, jsonNRObjCmd, cdata, objc, objv);
   -}
   -

-//}}}
void free_interp_cx(ClientData cdata) //{{{
{
struct interp_cx* l = cdata;
@@ -2673,12 +2626,16 @@
}

//}}}
+extern DLLEXPORT
int Rl_json_Init(Tcl_Interp* interp) //{{{
{
struct interp_cx* l = NULL;

   - Tcl_Namespace* rljsonNs = NULL;

+#ifdef USE_TCL_STUBS
if (Tcl_InitStubs(interp, "8.5", 0) == NULL)
return TCL_ERROR;
+#endif // USE_TCL_STUBS

Tcl_RegisterObjType(&json_type);

@@ -2687,7 +2644,6 @@
Tcl_IncrRefCount(l->tcl_true = Tcl_NewStringObj("1", 1));
Tcl_IncrRefCount(l->tcl_false = Tcl_NewStringObj("0", 1));
Tcl_IncrRefCount(l->tcl_empty = Tcl_NewStringObj("", 0));

   -

   Tcl_IncrRefCount(l->json_null = JSON_NewJvalObj(JSON_NULL, NULL));

   // Ensure the empty string rep is considered "shared"
   Tcl_IncrRefCount(l->tcl_empty);
   @@ -2696,20 +2652,16 @@
   l->kc_count = 0;
   memset(&l->freemap, 0xFF, sizeof(l->freemap));
   -

   Tcl_SetAssocData(interp, "rl_json", NULL, l);
   -
   -

   Tcl_NRCreateCommand(interp, "::rl_json::json", jsonObjCmd, jsonNRObjCmd,
   NULL, free_interp_cx);
   -

   TEST_OK(Tcl_EvalEx(interp, "namespace eval ::rl_json {namespace export
   *}", -1, TCL_EVAL_DIRECT | TCL_EVAL_GLOBAL));


   - rljsonNs = Tcl_CreateNamespace(interp, "::rl_json", NULL, NULL);
   - Tcl_CreateObjCommand(interp, "::rl_json::json", jsonObjCmd,
   (ClientData)l, free_interp_cx);


   - TEST_OK(Tcl_PkgProvide(interp, PACKAGE_NAME, PACKAGE_VERSION));


   - Tcl_Export(interp, rljsonNs, "json", 0);
   -
   - TEST_OK(Tcl_PkgProvide(interp, PACKAGE_NAME, PACKAGE_VERSION));

return TCL_OK;

}

//}}}

-/* Local Variables:
*/ -/* tab-width: 4
*/ -/* c-basic-offset: 4
*/ -/* End: */
// vim: foldmethod=marker foldmarker={{{,}}} ts=4 shiftwidth=4
diff -ruN rl_json/generic/main.h rl_json_el/generic/main.h
--- rl_json/generic/main.h 2017-05-23 15:21:09.412122000 +0200
+++ rl_json_el/generic/main.h 2017-05-02 15:50:15.462640200 +0200
@@ -11,7 +11,7 @@
#include <math.h>
#include <stddef.h>
#include <stdint.h>
-#include <sys/time.h>
+//#include <sys/time.h>
#include "parser.h"

#define STRING_DEDUP_MAX 16
@@ -38,55 +38,9 @@
int closed;
};

-struct foreach_iterator {

   - int data_c;
   - Tcl_Obj** data_v;
   - int data_i;
   - int var_c;
   - Tcl_Obj** var_v;
   - int is_array;
   -
   - // Dict search related state - when iterating over JSON objects
   - Tcl_DictSearch search;
   - Tcl_Obj* k;
   - Tcl_Obj* v;
   - int done;
   -};
   -

-struct foreach_state {

   - unsigned int loop_num;
   - unsigned int max_loops;
   - unsigned int iterators;
   - struct foreach_iterator* it;
   - Tcl_Obj* script;
   - Tcl_Obj* res;
   -};
   -

void append_to_cx(struct parse_context* cx, Tcl_Obj* val);
Tcl_Obj* JSON_NewJvalObj(int type, Tcl_Obj* val);

Tcl_Obj* new_stringobj_dedup(struct interp_cx* l, const char* bytes, int
length);

   -

-// Taken from tclInt.h:
-#if !defined(INT2PTR) && !defined(PTR2INT)
-# if defined(HAVE_INTPTR_T) || defined(intptr_t)
-# define INT2PTR(p) ((void *)(intptr_t)(p))
-# define PTR2INT(p) ((int)(intptr_t)(p))
-# else
-# define INT2PTR(p) ((void *)(p))
-# define PTR2INT(p) ((int)(p))
-# endif
-#endif
-#if !defined(UINT2PTR) && !defined(PTR2UINT)
-# if defined(HAVE_UINTPTR_T) || defined(uintptr_t)
-# define UINT2PTR(p) ((void *)(uintptr_t)(p))
-# define PTR2UINT(p) ((unsigned int)(uintptr_t)(p))
-# else
-# define UINT2PTR(p) ((void *)(p))
-# define PTR2UINT(p) ((unsigned int)(p))
-# endif
-#endif

   -

#endif
diff -ruN rl_json/generic/parser.h rl_json_el/generic/parser.h
--- rl_json/generic/parser.h 2017-05-23 15:21:09.414127300 +0200
+++ rl_json_el/generic/parser.h 2017-05-03 13:40:55.959259200 +0200
@@ -31,10 +31,9 @@
Tcl_Obj* tcl_true;
Tcl_Obj* tcl_false;
Tcl_Obj* tcl_empty;

   - Tcl_Obj* json_null;
   Tcl_HashTable kc;
   int kc_count;
   - long long freemap[(KC_ENTRIES / (8*sizeof(long long)))+1]; // long
   long for ffsll


   - unsigned long freemap[(KC_ENTRIES / (8*sizeof(unsigned long)))+1]; //
   long long for ffsll
   struct kc_entry kc_entries[KC_ENTRIES];
   };

diff -ruN rl_json/generic/tclstuff.h rl_json_el/generic/tclstuff.h
--- rl_json/generic/tclstuff.h 2017-05-23 15:21:09.414127300 +0200
+++ rl_json_el/generic/tclstuff.h 2017-05-03 13:41:26.583728900 +0200
@@ -10,19 +10,19 @@
(Tcl_ObjCmdProc *) c_cmd,
(ClientData *) NULL, NULL );

-#define THROW_ERROR( msg... )
+#define THROW_ERROR( ... )
{
Tcl_Obj *res;
res = Tcl_GetObjResult( interp ); \

   -

     Tcl_AppendStringsToObj( res, msg, NULL ); \



   -

     Tcl_AppendStringsToObj( res, ##__VA_ARGS__, NULL ); \
     return TCL_ERROR;			\

   }

-#define THROW_ERROR_LABEL( label, var, msg... )
+#define THROW_ERROR_LABEL( label, var, ... )
{
Tcl_Obj *res;
res = Tcl_GetObjResult( interp ); \

   -

     Tcl_AppendStringsToObj( res, msg, NULL ); \



   -

     Tcl_AppendStringsToObj( res, ##__VA_ARGS__, NULL ); \
     var = TCL_ERROR; \
     goto label; \

   }
   `

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/RubyLane/rl_json/issues/14>, or mute the thread

**Comment by ecky-l** [comment]
Hi,

I updated the patch. Its now based on the latest master commit (7b580f) and I did a "git format-patch HEAD^" to make the differences more readable.
I would create a pull request as well, but I've never done this before and apparently it requires push access to the repository, to create a new branch which can then be set as pull request. Don't know whether there is another way...

The patch does not include the build system. Building Tcl extensions on windows is a mess, imo. There is no usable way to do it, except with MinGW (and the MingW compilers are not very good in later releases, it seems... this extension has been compiled into a binary DLL of ~400kb size with gcc 6.3, whereas MSVC creates a DLL of size 89kb).
I wish there would be official CMake support for Tcl and extensions, but there isn't. So I usually create an MSVC project manually, compile the DLL inside the IDE and handcraft the pkgIndex.tcl file... luckily I don't have to do that often ;-).

> The BitScanForward function seemed like a reasonable alternative on windows but that area is really subtle so it would have to be very deeply understood to safely change. The reason for all this complexity is that it gives the compiler and standard libraries a fighting chance of being able to use one of the machine code opcodes dedicated to that job

I guess so. But I think _BitScanForward() is the way to go for windows. According to the documentation it is an abstraction for various low (machine) level details with the bitshift operation. It could be done manually as you say for the other branch (I haven't yet looked at that implementation), and I initially thought about doing so as well. But I think using _BitScanForward() is better.
As for the benchmarks, I haven't run them yet on windows, it would require some tweaking to the bench code too I guess, and so far I haven't had the need to measure performance with rl_json.

> the encoding issue in the tests sounds like the system encoding is something other than utf-8

Yes indeed it was. A "encoding system utf-8" at the top of tests/all.tcl does the trick. With this line, all the tests run through and are successful on windows as well.

[0001-proposal-for-rl_json-compile-on-windows.zip](https://github.com/RubyLane/rl_json/files/1033609/0001-proposal-for-rl_json-compile-on-windows.zip)

**Comment by cyanogilvie** [comment]
Hi, thanks for updating the patch.  I can work directly with the patch, but
if you want to create a pull request you first fork the project (which
gives you your own github fork), make your changes and push to your copy of
the project, then create a pull request based on those commits (github
remembers that it was forked from the parent project and handles all the
details).

I'm a bit concerned about the type changes (long long) -> (unsigned long).
As far as I can see, it results in a buffer overrun (on platforms that use
ffsll at least).  The type isn't arbitrary - it's a packed bitmap where
every bit is significant, so type correctness is critical.  Errors in that
won't necessarily show up in the tests (but probably would under valgrind
on a very large and varied set of documents.  Do you have some proof that
the type changes are safe?

**Comment by ecky-l** [comment]
Hello,

Hm no I don't have evidence that the type change is correct, apart from the fact that the tests still work. I am also not absolutely sure about the type change.. my thoughts were that long long has the same range for positive values as unsigned long, and since it is used as bitmap in ffsll() to find the least significant bit, it would work as well if the values are never negative. But honestly I don't know whether negative values are possible, or what are the real consequences of the shorter byte size, though.

Anyway, the windows _BitScanForward() function works a bit different than ffsll(), and it takes unsigned long as input. I got a compiler warning when using long long with BitScanForward(), and I was more scared about that than changing long long to unsigned long. If you think we should stick to long long, I think we should do so.

**Comment by cyanogilvie** [comment]
Well long is guaranteed to be at least 32 bits, and long long at least 64
bits, so they're not interchangeable (although on a particular platform
they could be the same, the standard just specifies the minimum sizes).
Since they aren't being interpreted as numbers, signed or unsigned isn't
relevant - they're just treated as a collection of bits.  If freemap is
declared as an array of unsigned long on a platform where sizeof(unsigned
long) != sizeof(long long), then each call to ffsll will access memory
beyond the current array element (or beyond the end of the array for the
last element).  I'd have to think about it, but I would expect that would
break things in nasty ways.

That entire mechanism could be implemented in an alternative way for
platforms without ffsll, but I'm reluctant to ifdef the code to that
extent, and to have two versions of such subtle code, one of which I can't
test.

I don't know when I'll get the time to analyse it properly to a level where
I'm confident that it's correct, and I don't want to delay MSVC any longer,
so I think I'll merge the rest of the patch and just use a polyfiller ffsll
for platforms where it isn't available.

That still leaves the issues with the build system, but I don't really want
to poke at that too deeply or upgrading to new versions of TEA will become
difficult.

**Comment by ecky-l** [comment]
Yes I see. If the value is zero, ffsll() reads into a 4 bytes memory region where it isn't supposed to read. And it evtl. returns the wrong value (if any of the 32 bits there is set). So it's not a good idea to use unsigned long with ffsll().
Hm. Would it be possible to use ffsl() instead of ffsll()?

**Comment by cyanogilvie** [comment]
I've merged support for MSVC based mostly on your patch, but using an ffsll polyfill from the #9 pull request.

I don't have that platform to test on though, could you give it a try and let me know if it works for you?

**Comment by cyanogilvie** [comment]
I think I've finally fixed this issue in a portable and performant way, using autoconf to detect the availability of various BSF implementations - first compiler intrinsics for gcc and clang, then the ffsll libc extensions in glibc and freebsd, then falling back to ffs, which is posix and should be available everywhere.  All compiled code that I've tested on x86-64 results in a bsf instruction, either using 64bit operands if the intrinsics or ffsll could be found, or 32bit operands if it had to fall back to ffs.  The freelist scanning adapts to the operand size for the different cases, so the cost of falling back to ffs over ffsll is that twice as many loop iterations happen to find a particular free bit, but the difference amounts to under 2% for parse-heavy benchmarks (the case most exposed to the performance of this area).

If you're still using rl_json, would you mind trying the latest version (0.11.0) and seeing if it works for you on Windows?  Also, if you want to work up a _BitScanForward() intrinsic based implementation that will be used on Windows instead of falling back to ffs I'd be happy to merge that (as long as it doesn't disrupt other things too much).  The performance difference should be minimal through, but the win from using ffs over the manual polyfill is significant - about 30% faster parsing.

Version 0.11.0 is mostly a drop-in replacement for older versions, but a lot has changed under the hood, and [json get_type] has been removed.  Various old methods have been deprecated, and path modifiers are deprecated, but other than get_type, all the old methods still work.  [json template] is now using a new engine under the hood that is much faster than the old one in cases where the resulting json is further manipulated.
