### ISSUE TITLE
How can I use the offset reported in an error?

### ISSUE THREAD

**Issue by thornjad** [RubyLane/rl_json#25]
When [usually inadvertently] trying to create invalid JSON, I may come across an error such as ```Illegal character at offset 48```. What does the `offset` actually mean here? Whenever I see it, the [in this case] 48th character of the JSON object doesn't make sense, nor does the 48th character in any string of sufficient length. How do I decode this error?

**Comment by cyanogilvie** [comment]
The offset is the 0-based offset into the string that is being parsed as JSON.  The string in question is returned as part of the -errorcode exception optoins.  I usually catch the {RL JSON PARSE} error and display an annotated version of the doc indicating the error position (inserting "(here -->)" before the offending character in this example):

```
try {
    json get {
        {
            "foo": {
                "bar": true,
            }
        }
    } foo bar
} trap {RL JSON PARSE} {errmsg options} {
    lassign [lrange [dict get $options -errorcode] 4 5] doc char_ofs
    puts stderr "$errmsg\n[string range $doc 0 $char_ofs-1](here -->)[string range $doc $char_ofs end]"
}
```

In this case the reason for the error is a "," where there shouldn't be one, but the actual syntax error is the "}" that follows the comma, since that character isn't legal after a comma in an object.

The output produced by the above example is:

```Error parsing JSON value: Illegal character at offset 37

		{
			"foo": {
				"bar": true,
			(here -->)}
		}
```

**Comment by thornjad** [comment]
That helped quite a bit, thank you so much! I might use that `trap`. Would there be benefit to putting that into the package itself so everyone can visually see where errors are?

**Comment by cyanogilvie** [comment]
I feel that the right interface to provide in the package is the exception info - properly displaying that is the domain of the application and relies on things the package can't know.  For instance, in some instances I'm displaying the error in a web context, so I use `<span>`s to highlight the error location, others it's a console script so I use colour escape sequences.  It can also be that the JSON doc is very large, and not appropriate to include the entire (several MB) string in the errormessage, which is likely to find its way into logs.  There may also be situations where the JSON contains sensitive info (application secret keys, passwords, personal info, etc), so keeping that out of the errormessage and leaving the handling up to the app is best I think.

I have added documentation for the exceptions now though - that was definitely missing, and included an this example for reporting parse errors.
