### ISSUE TITLE
Is there a better way to dynamicly create nested array

### ISSUE THREAD

**Issue by Bumshakalaka** [RubyLane/rl_json#26]
Hi,
I've been using rl_json a lot. Super handy TCL extension in data exchange.
Recently I found that I miss a function to create array dynamic. Something like 'lappend'.
Please check the code bellow:

```tcl
package require rl_json
#generate list of JSON object to work with
set lines [list]
for {set i 0} {$i < 10} {incr i} {
	rl_json::json set line  tag  [rl_json::json new string marker$i]
	rl_json::json set line  data [rl_json::json new string "dummy data$i"]
	lappend lines $line
}
#puts $lines
#{{"tag":"marker0","data":"dummy data0"}} {{"tag":"marker1","data":"dummy data1"}} {{"tag":"marker2","data":"dummy data2"}} \
#{{"tag":"marker3","data":"dummy data3"}} {{"tag":"marker4","data":"dummy data4"}} {{"tag":"marker5","data":"dummy data5"}} \
#{{"tag":"marker6","data":"dummy data6"}} {{"tag":"marker7","data":"dummy data7"}} {{"tag":"marker8","data":"dummy data8"}} \
#{{"tag":"marker9","data":"dummy data9"}}

#Create main JSON object
set d_json [rl_json::json template {{
            "id": "~S:id",
            "tStamp": "~N:tStamp",
            "lines": [{
                "tag": "~S:tag",
                "data": "~S:data"
            }]
        }} [dict create \
            tStamp [clock milliseconds]\
            id "obj13"\
            tag "marker"\
            data "dummy data"]]
#{"id":"obj13","tStamp":1571222639778,"lines":[{"tag":"marker","data":"dummy data"}]}
puts [rl_json::json pretty $d_json]

#Append JSON objects (lines) to array in main JSON object (d_json)
foreach line $lines {
	::rl_json::json set d_json lines [string replace [::rl_json::json extract $d_json lines] end end ",$line\]"]
}
#10 lines - 120 microseconds per iteration
#100 lines - 7302 microseconds per iteration
#1000 lines - 944830 microseconds per iteration

#puts [rl_json::json pretty $d_json]
```

to dynamic add new object to the array I use such ugly construction:
```tcl
::rl_json::json set d_json lines [string replace [::rl_json::json extract $d_json lines] end end ",$line\]"]
```

There is a lot of allocation which makes it very slow for 20+ objects in array (see the snippet above)

I was looking for something like lappend or append instead of set, something like this:
```tcl
::rl_json::json append d_json lines $line
```
or
```tcl
::rl_json::json append d_json lines [rl_json::json new json $line]
```
but I couldn't find.

Is there any better way to build array than take existing array and do use string operation on it and than reassign to JSON object?

Thanks.

**Comment by cyanogilvie** [comment]
I think you want something like the following:
```
set d_json  [json template {
    {
        "id":       "~S:id",
        "tStamp":   "~N:tStamp",
        "lines":    []
    }
} [dict create \
    tStamp  [clock milliseconds] \
    id      obj13
]]

set n   1000
puts "Adding $n lines: [time {
    for {set i 0} {$i < $n} {incr i} {
        set tag     marker$i
        set data    "dummy data$i"
        json set d_json lines end+1 [json template {
            {
                "tag":  "~S:tag",
                "data": "~S:data"
            }
        }]
    }
}]"
```

Using `json set` you can append or prepend elements to an existing array, by setting offsets after the end of the array (like "end+1") or before the beginning (like "-1").  It's an idiom I use all the time, and much faster (and safer, more readable) than having to parse each time:

10 lines: 49 microseconds per iteration
100 lines: 313 microseconds per iteration
1000 lines: 2885 microseconds per iteration
1000000 lines: 5673994 microseconds per iteration (or about 3 sec if using a dictionary rather than variables)

So, roughly linear with the number of lines, at around 5 microseconds to create a new template and append it to the array.  Prepending is the same.

Under the hood what is happening is that the Tcl_Obj you're passing is just being Tcl_ListObjAppendElement to the obj holding the array elements, which just stores a pointer to it and increments the refcount, very fast.  In the times above, the vast majority of the time is spent constructing the new objects that will be added to the array, if a static object is used instead, adding 1 million elements takes 0.7 seconds.

Also note you can use `json unset` on an array element to trim it out, with similar efficiency.  It's a nice way to implement queues.

I don't use it as often as the other techniques I mentioned above, but you're not limited to appending or prepending the element immediately outside the bounds of the current array, you can set one far out to extend (will nulls) the missing elements:

```
set foo {[]}
json set foo 10 {"dummy"}
# $foo is [null,null,null,null,null,null,null,null,null,"dummy"]
for {set i 0} {$i < 10} {incr i} {
    json set foo $i [json new number $i]
}
```

Doing it like that shaves off a small bit of time when adding a huge number of elemens because it cuts down on the reallocs to store the pointers as you grow the array bit by bit.

**Comment by Bumshakalaka** [comment]
Wow:) Thanks for the tip about offset for `set` and `unset` command. This is what I was missing.
It would be good to update the documentation about the possibility to use offset in `set` and `unset`

Anyhow, now if I use:
```tcl
::rl_json::json set d_json lines end+1 $line
```
the timing is fantastic now.
587us vs 944830us for 1000 objects
I'm appending already prepared JSON object.

Again, thanks a lot for comprehensive answer.

**Comment by cyanogilvie** [comment]
Documentation added :)
