### ISSUE TITLE
Issue with using dict with variables with json set

### ISSUE THREAD

**Issue by markjanssenpon** [RubyLane/rl_json#28]
There seems to be a bug when trying to use `dict with` variables in `json set`:

Example

```tcl
% package require rl_json
0.9.11

% set a {test {{"a":"b"}}}
% dict with a { rl_json::json get $test a }
b

% dict with a { rl_json::json set test a d }
Error parsing JSON value: Illegal character at offset 0


```

**Comment by dbohdan** [comment]
I can reproduce this with rl_json 0.9.11 but not 0.11.0 (the latest tag).

**Comment by mpcjanssen** [comment]
Will try with latest

**Comment by markjanssenpon** [comment]
Using head `0.11.0` fixes the issue.

**Comment by cyanogilvie** [comment]
Yeah, that shorthand syntax was invalid until a recent version (0.10 I
think).  The string 'd' isn't valid JSON.  Recent versions will treat that
as equivalent to [json string d] for convenience.

**Comment by mpcjanssen** [comment]
@cyanogilvie I don't understand what the string d has to do with this issue. Am I missing something?

**Comment by cyanogilvie** [comment]
In the code example with this issue, a key is set in a json object in the
"test" variable (that it's a bound variable to a dictionary key isn't
relevant here).  The statement is:

rl_json::json set test a d

[json set] takes /JSON/ as the value to set though (the last arg), and the
1 character long string "d" isn't valid JSON.  So an error is thrown while
trying to parse "d" as JSON, before adding it to the object.  The correct
way to do this is:

rl_json::json set test a [json string d]
# or
rl_json::json set test a {"d"}

However, newer versions of rl_json have been extended into this error space
to allow it to imply the type the programmer probably intended:

rl_json::json set test a 123       ;# Sets "123" as a JSON number.
Anything that can convert to a number will be added as one.
rl_json::json set test a true      ;# Sets as a JSON boolean value "true".
The strings "true" and "false" get this special treatment.
rl_json::json set test a null      ;# Sets as a JSON null.
rl_json::json set test a d         ;# Sets as a JSON string "d".  Any
string that doesn't match the above rules will be added as a string.

With the exception of the last case (falling back to string) the implicit
conversions are actually faster than manually constructing the JSON value
with [json number 123] or similar.  The string fallback is slower because
it has to go through a failed attempt to convert to a number first.  When
the intent is to add a string I recommend always explicitly doing [json
string foo] instead of using this DWIM fallback, for efficiency and also to
avoid the surprising behaviour that the document will contain a JSON type
other than string if the string happens to match one of the other patterns
above by accident.  It's fine for code literals, and quite efficient
because the Tcl_Obj in the literal table remembers that it is a JSON type,
but for anything else it's a bit unsafe.  There is some more discussion of
this mechanism in the json set section of the man page.

**Comment by mpcjanssen** [comment]
@cyanogilvie thanks for the explanation.
