### ISSUE TITLE
Create releases ?

### ISSUE THREAD

**Issue by rkeene** [RubyLane/rl_json#5]
Currently there are no releases of this software... is it at a point where it is stable to use ?  A release would be helpful for referring to where to download a specific version of this package.

**Comment by cyanogilvie** [comment]
It is in a stable state (we're using it heavily in production).  There is one known bug (exercised in test template-3.4) - a missing variable for an object key interpolation will produce a JSON doc with null for that key instead of throwing an error.

At this point I would be happy calling it 1.0 and creating a release, but there is some support for getting it into the core, so I'm busy with a TIP for that.  I expect that the API will change as a result of those discussions, so if it does make it through and get accepted I'll change the API of this package to match and release that as 1.0.
